image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-master:
  stage: build
  script:
    - deployment/docker_build.sh
    - deployment/docker_push.sh
  only:
    - master

build:
  stage: build
  script:
    - deployment/docker_build.sh $CI_COMMIT_REF_SLUG
    - deployment/docker_push.sh  $CI_COMMIT_REF_SLUG
  except:
    - master
